# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtWidgets, uic


class Calculator (QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        uic.loadUi("calculator.ui", self)

        # Проверка элементов
        required_widgets = [
            'btn_0', 'btn_1', 'btn_2', 'btn_3', 'btn_4',
            'btn_5', 'btn_6', 'btn_7', 'btn_8', 'btn_9',
            'btn_plus', 'btn_minus', 'btn_multiply',
            'btn_division', 'btn_equal', 'btn_clear', 'display'
        ]

        for widget in required_widgets:
            if not hasattr(self, widget):
                raise AttributeError(f"Элемент {widget} не найден!")

        # Инициализация
        self.current_text = ""
        self.operation = None
        self.first_num = 0

        # Подключение кнопок
        self.connect_buttons()

    def connect_buttons(self):
        """Подключает все кнопки"""
        # Цифры
        for i in range(10):
            getattr(self, f'btn_{i}').clicked.connect(
                lambda checked, x=str(i): self.add_digit(x))

        # Операции
        self.btn_plus.clicked.connect(lambda: self.set_operation('+'))
        self.btn_minus.clicked.connect(lambda: self.set_operation('-'))
        self.btn_multiply.clicked.connect(lambda: self.set_operation('*'))
        self.btn_division.clicked.connect(lambda: self.set_operation('/'))

        # Управление
        self.btn_equal.clicked.connect(self.calculate)
        self.btn_clear.clicked.connect(self.clear)

    def add_digit(self, digit):
        """Обработка цифровых кнопок"""
        self.current_text += digit
        self.display.setText(self.current_text)

    def set_operation(self, op):
        """Обработка +-*/"""
        if not self.current_text:
            return

        try:
            self.first_num = float(self.current_text)
            self.operation = op
            self.current_text = ""
        except ValueError:
            self.display.setText("Error")
            self.current_text = ""

    def calculate(self):
        """Вычисление результата"""
        if self.operation and self.current_text:
            try:
                second_num = float(self.current_text)
                if self.operation == '+':
                    result = self.first_num + second_num
                elif self.operation == '-':
                    result = self.first_num - second_num
                elif self.operation == '*':
                    result = self.first_num * second_num
                elif self.operation == '/':
                    result = self.first_num / second_num if second_num != 0 else "Error: Division by zero"

                self.display.setText(str(result))
                self.current_text = str(result)
                self.operation = None
            except Exception as e:
                self.display.setText("Error")
                self.current_text = ""

    def clear(self):
        """Сброс калькулятора"""
        self.current_text = ""
        self.operation = None
        self.first_num = 0
        self.display.setText("0")


if __name__ == "__main__":
    app = QtWidgets.QApplication([])
    window = Calculator()
    window.show()
    app.exec_()